openapi: 3.1.0
info:
  title: AxisCore API
  version: 1.0.0
paths:
  /v1/auth/token:
    post:
      summary: Obtain an access token (Client Credentials)
      description: Exchange client credentials for a short-lived Bearer token.
      operationId: postAuthToken
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [grant_type]
              properties:
                grant_type:
                  type: string
                  enum: [client_credentials]
                scope:
                  type: string
                  description: Space-delimited scopes.
      responses:
        "200":
          description: Token issued
          headers:
            X-RateLimit-Limit:
              $ref: "#/components/headers/RateLimitLimit"
            X-RateLimit-Remaining:
              $ref: "#/components/headers/RateLimitRemaining"
            X-RateLimit-Reset:
              $ref: "#/components/headers/RateLimitReset"
          content:
            application/json:
              schema:
                type: object
                required: [access_token, token_type, expires_in]
                properties:
                  access_token:
                    type: string
                    description: JWT or opaque token
                  token_type:
                    type: string
                    enum: [Bearer]
                  expires_in:
                    type: integer
                    example: 3600
                  scope:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Invalid client credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          description: Rate limited
          headers:
            Retry-After:
              schema:
                type: integer
              description: Seconds to wait before retrying.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  headers:
    RateLimitLimit:
      schema:
        type: integer
      description: Requests allowed per minute.
    RateLimitRemaining:
      schema:
        type: integer
      description: Requests remaining in current window.
    RateLimitReset:
      schema:
        type: integer
      description: Unix timestamp when the window resets.
  schemas:
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        request_id:
          type: string
        details:
          type: object
          additionalProperties: true
